name: testsiteforjed
favicon: null
layout_spectrum: 0.559161891695112
typography_spectrum: 0.6889799456112087
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.18997080950066447
  lightness: 0.10822700941935182
  saturation: 0.17470555542968214
  rhythmicContrast: 0.8324770152103156
purpose: []
