name: testsiteforjed
favicon: null
layout_spectrum: 0.25076
typography_spectrum: 0.35436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000507'
    - '#f6ffff'
    - '#3d3d3d'
    - '#ecdb33'
    - '#ab7865'
  brandStrength: 0
  lightness: 0
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
